editor: nvim

dashboards:
  - name: Demo
    layout:
      direction: row
      children:
        - direction: column
          weight: 2
          children:
            - panel: alertmanager
              params:
                filter: all
            - panel: kubectl-issues
              params:
                command: pods
                contexts:
                  - prod-eu1
                  - stage-eu1
                  - dev-eu1
                args:
                  - '-A'
        - direction: column
          weight: 2
          children:
            - direction: column
              children:
                - panel: jira
                  params:
                    jql: assignee = currentUser()
                - panel: github-notifications
                  weight: 2
            - direction: column
              children:
                - panel: github-prs
                  params:
                    query: author:@me is:open
                - panel: github-issues
                  params:
                    query: assignee:@me is:open
        - direction: column
          children:
            - panel: apple-calendar
            - panel: ricoberger-notes
              weight: 2
              params:
                dir: '~/notes'
            - panel: apple-mail
